### ISSUE TITLE
for some reason byyz cannot check his last.fm

### ISSUE THREAD

**Issue by k-e-l-p** [nojusr/Taigabot3#21]
Here's a traceback:
```python
Task exception was never retrieved
future: <Task finished coro=<nowplaying() done, defined at /home/nojus/programming/paprika/plugins/last-fm.py:128> exception=KeyError('toptags')>
Traceback (most recent call last):
  File "/home/nojus/programming/paprika/plugins/last-fm.py", line 190, in nowplaying
    tags = _pull_track_tags(lastfm_key, title, artist)
  File "/home/nojus/programming/paprika/plugins/last-fm.py", line 75, in _pull_track_tags
    tags_json = response.json()['toptags']['tag'][0:5]
KeyError: 'toptags'
```

**Comment by typing-noise** [comment]
it works with mymusichistory and mymusichistory__ but not with a single _

**Comment by k-e-l-p** [comment]
i think it has to do with the fact that his current song has no tags
and therefore it screws up the json parsing

**Comment by ineeee** [comment]
songs with no tags work fine:

    <ine> .np adrift
    <paprika> adrift is listening to "Scopes" [-snip-], Play count: 1, Tags: none.

**Comment by k-e-l-p** [comment]
seems to be a specific case, i cannot tell what's going wrong with it.
